// catalog
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'

// cart
export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART'
export const ADD_PRODUCT_IN_CART = 'ADD_PRODUCT_IN_CART'
export const REMOVE_PRODUCT_IN_CART = 'REMOVE_PRODUCT_IN_CART'
export const ALL_REMOVE_PRODUCT_IN_CART = 'ALL_REMOVE_PRODUCT_IN_CAR'
